export const plans = [
  {
    id: "starter",
    name: "Starter",
    description: "Perfect for small businesses just getting started online.",
    monthlyPrice: 299,
    projectPrice: 999,
    popular: false,
    features: [
      { text: "Social Media Management (2 platforms)", included: true },
      { text: "SEO Optimization (on-page)", included: true },
      { text: "Content Creation (8 posts/month)", included: true },
      { text: "Basic Branding & Identity", included: true },
      { text: "Landing Page Design", included: true },
      { text: "Paid Advertising", included: false },
      { text: "E-commerce Store", included: false },
      { text: "Dedicated Account Manager", included: false },
    ],
    cta: "Get Started",
    ctaLink: "/contact",
  },
  {
    id: "growth",
    name: "Growth",
    description: "For growing businesses ready to scale their digital presence.",
    monthlyPrice: 699,
    projectPrice: 2499,
    popular: true,
    features: [
      { text: "Social Media Management (4 platforms)", included: true },
      { text: "SEO Optimization (on-page & off-page)", included: true },
      { text: "Content Creation (20 posts/month)", included: true },
      { text: "Full Branding & Identity", included: true },
      { text: "Custom Website Design", included: true },
      { text: "Paid Advertising (Google & Meta)", included: true },
      { text: "E-commerce Store", included: false },
      { text: "Dedicated Account Manager", included: false },
    ],
    cta: "Start Growing",
    ctaLink: "/contact",
  },
  {
    id: "pro",
    name: "Pro",
    description: "The complete solution for brands that want to dominate their market.",
    monthlyPrice: 1299,
    projectPrice: 4999,
    popular: false,
    features: [
      { text: "Social Media Management (all platforms)", included: true },
      { text: "SEO Optimization (full strategy)", included: true },
      { text: "Content Creation (unlimited)", included: true },
      { text: "Premium Branding & Identity", included: true },
      { text: "Custom Website + E-commerce Store", included: true },
      { text: "Paid Advertising (Google, Meta & TikTok)", included: true },
      { text: "E-commerce Store", included: true },
      { text: "Dedicated Account Manager", included: true },
    ],
    cta: "Go Pro",
    ctaLink: "/contact",
  },
]